<a href="https://colab.research.google.com/github/Jeevesh8/sem-6/blob/main/AI/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing Numpy

In [2]:
import numpy as np

## Creating a Numpy Array

In [3]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x, type(x))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


## Various Ways of indexing

In [ ]:
x[1,2]

6

In [ ]:
x[:,1]

array([2, 5, 8])

In [ ]:
x[:,2]

array([3, 6, 9])

In [ ]:
x[:-1, :-1]

array([[1, 2],
       [4, 5]])

In [ ]:
x[...]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x[:2,...]

array([[1, 2, 3],
       [4, 5, 6]])

## Basic Addition

In [ ]:
x+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
x-2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

## Basic Data Types in Numpy

In [ ]:
x.dtype

dtype('int64')

In [ ]:
np.array(['ramesh', 'suresh']).dtype

dtype('<U6')

In [ ]:
np.array(['ramu', 'rami']).dtype

dtype('<U4')

## Symbols for Various DataTypes

`i` - integer

`b` - boolean

`u` - unsigned integer

`f` - float

`c` - complex float

`m` - timedelta

`M` - datetime

`O` - object

`S` - string

`U` - unicode string

`V` - fixed chunk of memory for other type ( void )

`>` means big-endian and `<` means little-endian.

And the number indicates the number of bytes. The 6 in '<U6' is the number of bytes occupied by each element of the array.

## Creating a DataType Object

In [ ]:
dt = np.dtype('<c8')

In [ ]:
np.array([2+3j, 5+6j], dtype=dt)

array([2.+3.j, 5.+6.j], dtype=complex64)

In [ ]:
dt.itemsize

8

### Structured Data Type

It is used to make numpy arrays over elements belonging to a structure. Each element must be of fixed size. 

In [ ]:
class lattitude:
    def __init__(self, lattitude):
        assert lattitude<=90, "Lattittude must be less than or equal to 90 degrees."
        assert lattitude>=-90, "Lattittude must be greater than or equal to -90 degrees."
        self.lat = lattitude

class longitude:
    def __init__(self, longitude):
        assert longitude<=180, "Longitude must be less than or equal to 180 degrees."
        assert longitude>=-180, "Longitude must be greater than or equal to -180 degrees."
        self.lon = longitude

In [ ]:
dt = np.dtype(lattitude, longitude)

In [ ]:
dt.itemsize

8

In [ ]:
y = np.array([(lattitude(0),longitude(0)), 
              (lattitude(-6.3572375290155), longitude(-63.572375290155))], dtype=dt)

In [ ]:
y[1][0].lat

-6.3572375290155

## 10 Methods in Numpy

In [8]:
#sorting an array
np.sort(-x, axis=1)

array([[-3, -2, -1],
       [-6, -5, -4],
       [-9, -8, -7]])

In [9]:
#Finding max
print(np.argmax(x), np.max(x), np.argmax(x, axis=1))

8 9 [2 2 2]


In [10]:
#Dot product
np.dot(x[0], x[1])

32

In [11]:
#Outer Product
np.outer(x[0], x[1])

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [12]:
#Determinant
np.linalg.det(x)

0.0

In [13]:
#Covariance Matrix
np.cov(x)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#Solving Ax=B
x = np.array([[3,4,5], [7,4,2], [9,7,1]])
np.linalg.solve(np.transpose(x), x[0])

array([ 1.0000000e+00, -5.6213824e-17, -1.4053456e-17])

In [22]:
#Finding which positions have value between 2 and 6
np.logical_and(x>2, x<6)

array([[ True,  True,  True],
       [False,  True, False],
       [False, False, False]])

In [23]:
#Getting EigenValues of a matrix
np.linalg.eig(x)

(array([13.4794913 , -4.02249696, -1.45699434]),
 array([[ 0.52137272,  0.67350283,  0.59068622],
        [ 0.52665752, -0.43949436, -0.79899766],
        [ 0.67141816, -0.59433883,  0.11266111]]))

In [32]:
#upper and lower triangular matrices
np.triu(x), np.tril(x)

(array([[3, 4, 5],
        [0, 4, 2],
        [0, 0, 1]]), array([[3, 0, 0],
        [7, 4, 0],
        [9, 7, 1]]))

In [33]:
#Cholesky Decomposition
np.linalg.cholesky(np.triu(x)*np.tril(x))

array([[3., 0., 0.],
       [0., 4., 0.],
       [0., 0., 1.]])

## Finding Unique Elements

In [34]:
np.unique(x)

array([1, 2, 3, 4, 5, 7, 9])